#Tokenizer

In [ ]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

veri = [
    'Bu bir örnek cümle.',
    'Bu bir başka örnek cümle.',
    'Bu bir üçüncü örnek cümle'
]


In [ ]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts(veri)

In [ ]:
sayısal_karsilik = tokenizer.texts_to_sequences(veri)
print('Kelime indeksleri:', tokenizer.word_index)


Kelime indeksleri: {'bu': 1, 'bir': 2, 'örnek': 3, 'cümle': 4, 'başka': 5, 'üçüncü': 6}


In [ ]:
for sayi in sayısal_karsilik:
  print(sayi)

[1, 2, 3, 4]
[1, 2, 5, 3, 4]
[1, 2, 6, 3, 4]


In [ ]:
sabit_uzunluk = pad_sequences(sayısal_karsilik, maxlen=5)
print(sabit_uzunluk)

[[0 1 2 3 4]
 [1 2 5 3 4]
 [1 2 6 3 4]]


#Embedding

In [ ]:
from keras.layers import Embedding
from keras.models import Sequential
import numpy as np

In [ ]:
giris_boyutu=len(tokenizer.word_index)+1
boyut=300
embdedding_layer=Embedding(input_dim=giris_boyutu,output_dim=boyut,input_length=5)
kimlikli_veri=embdedding_layer(np.array(sabit_uzunluk))


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [ ]:
print('Embedding Katman sonucu:', kimlikli_veri)


Embedding Katman sonucu: tf.Tensor(
[[[-0.03456409  0.02869168  0.02958084 ... -0.03808277  0.01828085
    0.00054977]
  [ 0.00047658 -0.02799212  0.03426016 ...  0.03799513  0.01543446
    0.00830938]
  [ 0.04760193  0.01450643 -0.02651408 ... -0.01891311 -0.04131765
    0.02046539]
  [-0.01298966 -0.01258125 -0.00172354 ...  0.03372258 -0.02991351
    0.00601517]
  [ 0.02644687 -0.03275388  0.04982126 ... -0.01567386  0.00831228
    0.01114267]]

 [[ 0.00047658 -0.02799212  0.03426016 ...  0.03799513  0.01543446
    0.00830938]
  [ 0.04760193  0.01450643 -0.02651408 ... -0.01891311 -0.04131765
    0.02046539]
  [-0.0208672  -0.03582174  0.04365322 ...  0.02267697  0.00981904
   -0.0303287 ]
  [-0.01298966 -0.01258125 -0.00172354 ...  0.03372258 -0.02991351
    0.00601517]
  [ 0.02644687 -0.03275388  0.04982126 ... -0.01567386  0.00831228
    0.01114267]]

 [[ 0.00047658 -0.02799212  0.03426016 ...  0.03799513  0.01543446
    0.00830938]
  [ 0.04760193  0.01450643 -0.02651408 ... -0.0